version: "3"
services:
  local-db:
    platform: linux/amd64 # 추가된 라인
    image: mysql:5.7 # 이미지
    container_name: local-db
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Seoul
    volumes:
      - /Users/bob/Documents/docker/mysql/datadir:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4 # 인코딩
      - --collation-server=utf8mb4_unicode_ci
#script
# create database boaz;
# create user 'boaz'@'%' identified by 'hello';
# flush privileges;
# grant all on boaz.* to 'boaz'@'%';
# flush privileges;
